-- Snowflake Integration Test Schema Setup
-- This script creates the necessary tables and functions for testing the Snowflake cache

-- Create schema for cache monitoring
CREATE SCHEMA IF NOT EXISTS CACHE;

-- Create table_log for monitoring table changes
CREATE TABLE IF NOT EXISTS CACHE.TABLE_LOG (
    ID INTEGER AUTOINCREMENT PRIMARY KEY,
    TABLE_NAME VARCHAR(255) NOT NULL,
    OPERATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    OPERATION_TYPE VARCHAR(10) DEFAULT 'UPDATE'
);

-- Create test tables for cache testing
CREATE TABLE IF NOT EXISTS API_KEYS (
    ID INTEGER AUTOINCREMENT PRIMARY KEY,
    KEY VARCHAR(255) UNIQUE NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER AUTOINCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) DEFAULT 'user',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Create function to log table changes
CREATE OR REPLACE PROCEDURE LOG_TABLE_CHANGE(TABLE_NAME VARCHAR, OPERATION_TYPE VARCHAR)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO CACHE.TABLE_LOG (TABLE_NAME, OPERATION_TIME, OPERATION_TYPE)
    VALUES (:TABLE_NAME, CURRENT_TIMESTAMP(), :OPERATION_TYPE);
    RETURN 'SUCCESS';
END;
$$;

-- Note: Snowflake doesn't support triggers like PostgreSQL
-- Instead, we'll use stored procedures and call them manually in tests
-- or use Snowflake's change tracking features if available
